### ISSUE TITLE
National characters not displayed on mobiles

### ISSUE THREAD

**Issue by kaaes** [kaaes/work_from_cafe#13]
There's a problem with Polish characters - they're missing from the Google font used (Puritan)

Solution 1: stop using Polish chars ;)
Solution 2: find nice free font with national characters

**Comment by nazgob** [comment]
pehaps sth from there: http://www.fontsquirrel.com/

**Comment by nazgob** [comment]
work fine on iPhone, you want to tell me that Android phone does not render Google font? :)

**Comment by kaaes** [comment]
nah, I changed it already for another font :)

so I guess I can close that issue

**Comment by nazgob** [comment]
cool, i'm pretty slow today :)
