### ISSUE TITLE
Cafes opening times?

### ISSUE THREAD

**Issue by maciej** [kaaes/work_from_cafe#3]
Adding cafes opening times could be useful IMVHO.

**Comment by kaaes** [comment]
I think you're absolutely right :) I'm going to add them as soon as I have a chance to check the places.

And thanks for the new place! :)

**Comment by nazgob** [comment]
Why not wait and give sb new a chance to contribute? At least that was my initial plan for that :)

**Comment by kaaes** [comment]
Why not :) I added opening hours to criteria. 

Maybe I'll also add this info to one of the places to set an example ;) (have to check it first)

**Comment by fharper** [comment]
Good idea, someone added this to the JSON file.
