### ISSUE TITLE
Need a collaborator?

### ISSUE THREAD

**Issue by fharper** [kaaes/work_from_cafe#49]
Hi,
I'm Fred, working with Christian. He told me about this repository, and as a remote worker as a traveler, I really liked it. Do you need a collaborator to manage the pull requests? I can help if you want.

Fred

**Comment by fharper** [comment]
My offer is still available since there is pull requests from 6 months ago :)

**Comment by kaaes** [comment]
Ok, that is really embarrassing :)
I just merged other pull requests but I have a small issue with yours - the indentation change rewrote everything and made the actual change quite difficult to read. Could you remove the commit that introduced it from pull request (7f0a529)?
Also we obviously could use another collaborator so if you're still interested I'd be very happy to add you!

**Comment by fharper** [comment]
I'll remove my commit, and I'll be happy to help, so go ahead, add me.

**Comment by fharper** [comment]
You can add me, and I'll manage the pull requests I made, thanks.

**Comment by kaaes** [comment]
I'm currently in Belgrade without my computer and with limited access to the internet so it might get a bit delayed but it will be the first thing I'll do when I get back on Sunday!

**Comment by fharper** [comment]
No worries :)

**Comment by fharper** [comment]
I was added as a collaborator.
